# Generated by Django 5.0.3 on 2024-03-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexify', '0002_farmer_acreage_farmer_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerecord',
            old_name='product',
            new_name='crop',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='acreage',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='crop',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Crop',
        ),
        migrations.CreateModel(
            name='FarmerCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexify.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexify.farmer')),
            ],
            options={
                'unique_together': {('farmer', 'crop')},
            },
        ),
    ]
