# Generated by Django 5.0.3 on 2024-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexify', '0003_rename_product_pricerecord_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
